# Generated by Django 2.1.5 on 2019-01-27 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_id', models.CharField(max_length=64, unique=True)),
                ('mac', models.CharField(max_length=12)),
                ('name', models.CharField(max_length=255)),
                ('_image', models.TextField(blank=True, db_column='image')),
            ],
        ),
    ]
