# Generated by Django 2.1.5 on 2019-01-27 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('badge', '0002_badge_secret'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthCode',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('long_lived', models.BooleanField(default=False)),
                ('last_used', models.DateTimeField(auto_now=True)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authcodes', to='badge.Badge')),
            ],
        ),
    ]
