# Generated by Django 2.1.5 on 2019-01-27 12:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badge', '0003_authcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='badge',
            name='registered_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 27, 12, 38, 11, 593475)),
            preserve_default=False,
        ),
    ]
