# Generated by Django 2.1.5 on 2019-01-28 18:16

import badge.models.app
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badge', '0005_auto_20190127_1341'),
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('version', models.IntegerField()),
                ('static', models.BooleanField(default=True)),
                ('blob', models.FileField(upload_to=badge.models.app.tar_path)),
            ],
        ),
        migrations.AddField(
            model_name='badge',
            name='changed_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='authcode',
            name='last_used',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='badge',
            name='registered_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterUniqueTogether(
            name='app',
            unique_together={('name', 'version')},
        ),
    ]
