# Generated by Django 2.1.5 on 2019-02-05 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badge', '0006_auto_20190128_1816'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='slug',
            field=models.SlugField(default=None),
            preserve_default=False,
        ),
    ]
