# Generated by Django 2.1.5 on 2019-02-05 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('badge', '0007_app_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='app',
            name='slug',
        ),
    ]
