# Generated by Django 2.1.5 on 2019-02-05 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('badge', '0008_remove_app_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='app',
            name='static',
        ),
    ]
