# Generated by Django 2.1.5 on 2019-02-06 10:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badge', '0009_remove_app_static'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='name',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(code='invalid_name', message='App name must be Alphanumeric', regex='^[a-zA-Z0-9]+$')]),
        ),
    ]
