# Generated by Django 2.1.5 on 2019-02-06 15:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badge', '0012_setting_talk_vote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='rating',
            field=models.SmallIntegerField(validators=[django.core.validators.RegexValidator(code='invalid_rating', message='Rating must be between zero and five starts', regex='^[0-5]$')]),
        ),
    ]
