# Generated by Django 2.1.5 on 2019-02-07 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('badge', '0013_auto_20190206_1651'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='setting',
            unique_together={('badge', 'key')},
        ),
    ]
