# Generated by Django 2.1.5 on 2019-02-07 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badge', '0015_auto_20190207_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='rating',
            field=models.SmallIntegerField(),
        ),
    ]
