# Generated by Django 2.1.5 on 2019-02-13 14:11

from django.db import migrations


def load_fixtures(apps, schema_editor):
    from django.core.management import call_command
    call_command("loaddata", "scopes")


def unload_fixtures(apps, schema_editor):
    Scope = apps.get_model("scopes", "Scope")
    Scope.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('badge', '0020_auto_20190213_1507'),
    ]

    operations = [
        migrations.RunPython(load_fixtures, reverse_code=load_fixtures),
    ]
