# Generated by Django 2.1.5 on 2019-02-27 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badge', '0021_load_intial_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='title',
            field=models.CharField(default='', max_length=42),
            preserve_default=False,
        ),
    ]
