# Generated by Django 2.1.5 on 2019-03-11 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badge', '0025_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='talk',
            name='agenda_id',
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='talk',
            name='slug',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
